In [1]:
import numpy as np
from itertools import product

In [3]:
a = np.arange(0,16).reshape(4,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
b = np.arange(0,4)

In [10]:
b

array([0, 1, 2, 3])

In [11]:
np.dot(b,a)

array([56, 62, 68, 74])

In [12]:
a = np.array([np.arange(5),np.arange(5),np.arange(5),np.arange(5)])

In [37]:
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [32]:
b = np.arange(4)

In [33]:
b

array([0, 1, 2, 3])

In [1]:
np.dot(np.transpose(a),b)

NameError: name 'np' is not defined

In [29]:
a-b

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [9]:
self_pos = np.array((1,2))
coins = np.array([(2,3),(3,5),(4,5)])

In [10]:
np.array(coins)

array([[2, 3],
       [3, 5],
       [4, 5]])

In [12]:
d = coins - self_pos

In [13]:
d

array([[1, 1],
       [2, 3],
       [3, 3]])

In [23]:
(2,7) in coins

True

In [54]:
coordinates = np.array(list(product(np.arange(0,17),np.arange(0,17))))
np.where((coordinates == [0, 3]).all(axis=1))[0][0]

3

In [55]:
field=np.array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [69]:
rows, cols = np.where(field == -1)

In [79]:
coords = np.array([rows, cols]).T

In [89]:
from collections import namedtuple
from collections import deque

In [83]:
Transition = namedtuple('Transition',
                        ('state', 'action', 'next_state', 'reward'))

In [127]:
a = deque()
a.append(Transition([1],'UP', [2], 4))
a.append(Transition([600],'DOWN', [2], 2))

In [128]:
a

deque([Transition(state=[1], action='UP', next_state=[2], reward=4),
       Transition(state=[600], action='DOWN', next_state=[2], reward=2)])

In [129]:
np.array(a)[-1,0]

[600]

In [132]:
[i for i in range(1,10)]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [159]:
init_beta = np.ones(5)
model = {'UP': init_beta, 
'RIGHT': init_beta, 'DOWN': init_beta,
'LEFT': init_beta, 'WAIT': init_beta, 'BOMB': init_beta}
model['DOWN'] = model['UP'] * 5 

In [160]:
vec_model = np.array(list(model.values()))
vec_model

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [161]:
list(model.keys())[np. argmax(np.dot(vec_model, np.arange(5)))]

'DOWN'

In [3]:
coin_coordinates = [(1,2),(3,4),(9,2)]
new_player_coor = (1,2)

In [5]:
np.linalg.norm(np.subtract(coin_coordinates,new_player_coor), axis=1)

array([0.        , 2.82842712, 8.        ])