In [2]:
import numpy as np

In [3]:
a = np.arange(0,16).reshape(4,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
b = np.arange(0,4)

In [10]:
b

array([0, 1, 2, 3])

In [11]:
np.dot(b,a)

array([56, 62, 68, 74])

In [12]:
a = np.array([np.arange(5),np.arange(5),np.arange(5),np.arange(5)])

In [37]:
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [32]:
b = np.arange(4)

In [33]:
b

array([0, 1, 2, 3])

In [35]:
np.dot(np.transpose(a),b)

array([ 0,  6, 12, 18, 24])

In [29]:
a-b

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])