In [25]:
import numpy as np
from itertools import product

In [3]:
a = np.arange(0,16).reshape(4,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
b = np.arange(0,4)

In [10]:
b

array([0, 1, 2, 3])

In [11]:
np.dot(b,a)

array([56, 62, 68, 74])

In [12]:
a = np.array([np.arange(5),np.arange(5),np.arange(5),np.arange(5)])

In [37]:
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [32]:
b = np.arange(4)

In [33]:
b

array([0, 1, 2, 3])

In [41]:
np.dot(np.transpose(a),b)

array([ 0,  6, 12, 18, 24])

In [29]:
a-b

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [9]:
self_pos = np.array((1,2))
coins = np.array([(2,3),(3,5),(4,5)])

In [10]:
np.array(coins)

array([[2, 3],
       [3, 5],
       [4, 5]])

In [12]:
d = coins - self_pos

In [13]:
d

array([[1, 1],
       [2, 3],
       [3, 3]])

In [23]:
(2,7) in coins

True

In [48]:
coordinates = np.array(list(product(np.arange(0,17),np.arange(0,17))))
np.where((coordinates == (0, 3)).all(axis=1))

(array([3], dtype=int64),)

In [45]:
coordinates

array([[ 0,  0],
       [ 0,  1],
       [ 0,  2],
       [ 0,  3],
       [ 0,  4],
       [ 0,  5],
       [ 0,  6],
       [ 0,  7],
       [ 0,  8],
       [ 0,  9],
       [ 0, 10],
       [ 0, 11],
       [ 0, 12],
       [ 0, 13],
       [ 0, 14],
       [ 0, 15],
       [ 0, 16],
       [ 1,  0],
       [ 1,  1],
       [ 1,  2],
       [ 1,  3],
       [ 1,  4],
       [ 1,  5],
       [ 1,  6],
       [ 1,  7],
       [ 1,  8],
       [ 1,  9],
       [ 1, 10],
       [ 1, 11],
       [ 1, 12],
       [ 1, 13],
       [ 1, 14],
       [ 1, 15],
       [ 1, 16],
       [ 2,  0],
       [ 2,  1],
       [ 2,  2],
       [ 2,  3],
       [ 2,  4],
       [ 2,  5],
       [ 2,  6],
       [ 2,  7],
       [ 2,  8],
       [ 2,  9],
       [ 2, 10],
       [ 2, 11],
       [ 2, 12],
       [ 2, 13],
       [ 2, 14],
       [ 2, 15],
       [ 2, 16],
       [ 3,  0],
       [ 3,  1],
       [ 3,  2],
       [ 3,  3],
       [ 3,  4],
       [ 3,  5],
       [ 3,  6],
       [ 3,  7