In [1]:
import numpy as np
from itertools import product
from collections import namedtuple
from collections import deque
import pickle
import matplotlib.pyplot as plt

In [5]:
with open("agent_code/kampfente_N-step-TD/fluctuations.pt", "rb") as file:
            fluctuations = pickle.load(file)

In [6]:
fluctuations

[0.917053100379138,
 -7.061341558452307,
 -3.556677916394211,
 0.9392031671593339,
 5.957867380539538,
 4.81301201987337,
 1.2280871232717503,
 4.3067289804536975,
 1.1246929286613443,
 3.8538243421386325,
 1.7331074621868527,
 3.9185527940894724,
 2.3426854722457207,
 4.808723690671089,
 3.9183542330026393,
 -0.9911865392390999,
 2.149772139185509,
 -2.055586295320743,
 0.010348150531444222,
 1.0443838238071592,
 -1.868963177589367,
 -0.3922565729104499,
 -1.4627766897713244,
 -10.998007577600887,
 -15.018069384701962,
 -16.084759075118974,
 -18.464428855129153,
 1.2257869123638887,
 -0.83878070529222,
 -4.3078137883248395,
 -0.885436503297819,
 2.3695929656217833,
 -0.5854329268332528,
 1.3662333100690007,
 5.395624534878302,
 1.2360534413070448,
 4.743072661358504,
 1.1174883258474708,
 4.169610983802454,
 1.0096206676840056,
 3.665633474310253,
 0.9115864608259523,
 3.222703212948079,
 1.507804029849868,
 2.972914451157697,
 0.7291310901250045,
 2.751813834516582,
 -0.1223629664889

In [3]:
a = np.arange(0,16).reshape(4,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
b = np.arange(0,4)

In [4]:
b

array([0, 2, 4, 6])

In [11]:
np.dot(b,a)

array([56, 62, 68, 74])

In [12]:
a = np.array([np.arange(5),np.arange(5),np.arange(5),np.arange(5)])

In [37]:
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [32]:
b = np.arange(4)

In [33]:
b

array([0, 1, 2, 3])

In [1]:
np.dot(np.transpose(a),b)

NameError: name 'np' is not defined

In [29]:
a-b

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [9]:
self_pos = np.array((1,2))
coins = np.array([(2,3),(3,5),(4,5)])

In [10]:
np.array(coins)

array([[2, 3],
       [3, 5],
       [4, 5]])

In [12]:
d = coins - self_pos

In [13]:
d

array([[1, 1],
       [2, 3],
       [3, 3]])

In [23]:
(2,7) in coins

True

In [54]:
coordinates = np.array(list(product(np.arange(0,17),np.arange(0,17))))
np.where((coordinates == [0, 3]).all(axis=1))[0][0]

3

In [55]:
field=np.array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [69]:
rows, cols = np.where(field == -1)

In [79]:
coords = np.array([rows, cols]).T

In [89]:
from collections import namedtuple
from collections import deque

In [8]:
Transition = namedtuple('Transition',
                        ('state', 'action', 'next_state', 'reward'))

In [85]:
a = deque()
a.append(Transition(np.array([1, 1, 1, 1]),'DOWN', [2], 4))
a.append(Transition(np.array([600, 3, 23, 23]),'DOWN', [2], 2))
a.append(Transition(np.array([600, 3, 23, 23]),'DOWN', [2], 2))
a.append(Transition(np.array([600, 3, 23, 23]),'DOWN', [2], 2))
a.append(Transition(np.array([600, 3, 23, 23]),'DOWN', [2], 2))

In [86]:
a

deque([Transition(state=array([1, 1, 1, 1]), action='DOWN', next_state=[2], reward=4),
       Transition(state=array([600,   3,  23,  23]), action='DOWN', next_state=[2], reward=2),
       Transition(state=array([600,   3,  23,  23]), action='DOWN', next_state=[2], reward=2),
       Transition(state=array([600,   3,  23,  23]), action='DOWN', next_state=[2], reward=2),
       Transition(state=array([600,   3,  23,  23]), action='DOWN', next_state=[2], reward=2)])

In [121]:
total_batch_size = np.shape(np.array(a))[0]
total_batch_size

5

In [148]:
np.stack(np.array(a)[:,0][np.where(np.array(a)[:,1]=='DOWN')])

TypeError: can only concatenate tuple (not "int") to tuple

In [89]:
np.take(np.array(a)[:,1], [0,1], axis = 0)

array(['DOWN', 'DOWN'], dtype=object)

In [149]:
np.where(np.array(a)[:,1]=='DOWN')[0] + 1

array([1, 2, 3, 4, 5], dtype=int64)

In [142]:
n = 3
idx = np.where(np.array(a)[:,1]=='DOWN')[0][:, None] + np.arange(n)

In [146]:
idx = np.where(idx >= 5, 0,idx)
idx

TypeError: '>=' not supported between instances of 'NoneType' and 'int'

In [147]:
k = total_batch_size-n+1
k

3

In [145]:
np.array(a)[:,3][idx[0:k]]

IndexError: arrays used as indices must be of integer (or boolean) type

In [112]:
for n in idx:
    try:
        print(np.array(a)[[n])
    except IndexError:
        print(np.zeros(3))

[4 2 2]
[2 2 2]
[2 2 2]
[0. 0. 0.]
[0. 0. 0.]


In [132]:
[i for i in range(1,10)]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [159]:
init_beta = np.ones(5)
model = {'UP': init_beta, 
'RIGHT': init_beta, 'DOWN': init_beta,
'LEFT': init_beta, 'WAIT': init_beta, 'BOMB': init_beta}
model['DOWN'] = model['UP'] * 5 

In [160]:
vec_model = np.array(list(model.values()))
vec_model

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [161]:
list(model.keys())[np. argmax(np.dot(vec_model, np.arange(5)))]

'DOWN'

In [3]:
coin_coordinates = [(1,2),(3,4),(9,2)]
new_player_coor = (1,2)

In [5]:
np.linalg.norm(np.subtract(coin_coordinates,new_player_coor), axis=1)

array([0.        , 2.82842712, 8.        ])