In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
print(a[1:])

[2, 3, 4, 5]


In [3]:
a = np.array([[1,2,3,4,5],[1,2,3,4,5]])
b = np.sum(a,axis = 0)
print(b)

[ 2  4  6  8 10]


In [5]:
d = np.array([1,2,3,4,5])
print(np.dot(d.T,2))

[ 2  4  6  8 10]


In [6]:
e = np.array([[1,1],[2,2]])
f = np.array([3,3])
np.dot(e,f)

array([ 6, 12])

In [ ]:
'''
        value = float('-inf')
        x = state_to_features(game_state)
        for a in ACTIONS:
            beta = self.model[a]
            weight = np.dot(x,beta)
            if weight > value: 
                value = weight
                move = a
        '''
