In [1]:
import numpy as np
from itertools import product 

In [3]:

a = [[(1,2),(3,4)],[(1,2)]]
A=np.array(a)
print(A)

[list([(1, 2), (3, 4)]) list([(1, 2)])]


In [13]:
coordinates = np.array(list(product(np.arange(0,17),np.arange(0,17))))

In [14]:
coor = coordinates[1]
print(coor)
print(a[coor])

[0 1]
[[1 2 1 1 0 1]
 [1 0 1 2 1 0]]


In [19]:
c = (2,0,0)
d = (1,0,0)
print(np.linalg.norm(np.subtract(c,d)))

1.0


In [33]:
def get_all_exploding_tiles(field) -> dict:
    '''
    For each pixel where we can place a bomb, we search all the tiles blowing up with that bomb

    :param field: input must be game_state_field (state itself is arbitrary)
    :return: dict where keys are coordinate tuples and values arrays of flattened coordinates
    '''
    
    np.where(field == -1,-1,0)     #set all walls to -1, rest to 0
    
    exploding_tiles = {}

    for i in range(17):
        for j in range(17):
            if field[i,j] == -1:
                continue
            coors_ij=[17*i + j]

            #first consider walking to the right, stop when encounter -1 or after 3 steps
            k,l = i,j
            while (field[k,l+1] !=-1) and np.abs(l-j)<3:
                l+=1
                coors_ij.append(17*k+l)
            #walking left:
            k,l = i,j
            while (field[k,l-1] !=-1) and np.abs(l-j)<3:
                l-=1
                coors_ij.append(17*k+l)
            #walking up:
            k,l = i,j
            while (field[k-1,l] !=-1) and np.abs(k-i)<3:
                k-=1
                coors_ij.append(17*k+l)
            #walking down
            k,l = i,j
            while (field[k+1,l] !=-1) and np.abs(k-i)<3:
                k+=1
                coors_ij.append(17*k+l)
            
            exploding_tiles[(i,j)] = np.array(coors_ij)

    return exploding_tiles


In [23]:
j = 0
k = j
i=0
field = np.array([[0,0,0,0,0,0,0,0,-1,0]])
while field[i,k+1] != -1 and np.abs(j-k)<3:  
    print(i,k+1)
    k+=1

0 1
0 2
0 3


In [24]:
dictionary = {(1,2):3}
dictionary[(1,2)]

3

In [35]:
field=np.array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
 [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [36]:
dictionary = get_all_exploding_tiles(field)

In [39]:
dictionary[(1,2)]

array([19, 20, 21, 22, 18])

In [9]:
A = np.array([(1,2),(1,2)])
np.linalg.norm(A, axis = 0)

array([1.41421356, 2.82842712])